const fs = [
  { name: "Schumann: Earth’s natural frequency", f: 7.83 },
  { name: "Otto: Immune system", f: 32 },
  { name: "Otto: Nervous system", f: 64 },
  { name: "Ohm: Low Ohm", f: 68.05 },
  { name: "Chakras: Earth star (Vasundhara)", f: 68.05, l: 336 },
  { name: "Organs: Stomach", f: 110 },
  { name: "Angels: Holy frequency", f: 111 },
  { name: "Organs: Pancreas", f: 117.3 },
  { name: "Chakras: Solar Plexus (Manipura)", f: 126.22, l: 307 },
  { name: "Cosmic: Sun", f: 126.22 },
  { name: "Healing: Blood circulation, sleep, and stress relief", f: 128 },
  { name: "Otto: Joints mobility", f: 128 },
  { name: "Ohm: Mid Ohm", f: 136.1 },
  { name: "Chakras: Heart (Anahata)", f: 136.1, l: 337 },
  { name: "Cosmic: Pluto", f: 140.25 },
  { name: "Chakras: Throat (Vishuddha)", f: 141.27 },
  { name: "Cosmic: Mercury", f: 141.27 },
  { name: "Cosmic: Mars", f: 144.72 },
  { name: "Cosmic: Saturn", f: 147.85 },
  { name: "Organs: Gall Bladder", f: 164.3 },
  { name: "Chakras: Crown (Sahasrara)", f: 172.06 },
  { name: "Solfeggio: Physical pain relief and stress relief", f: 174 },
  { name: "Organs: Colon", f: 176 },
  { name: "Cosmic: Jupiter", f: 183.58 },
  { name: "Chakras: Root (Muladhara)", f: 194.18 },
  { name: "Cosmic: Earth", f: 194.18 },
  { name: "Cosmic: Uranus", f: 207.36 },
  { name: "Chakras: Sacral (Svadhisthana)", f: 210.42 },
  { name: "Cosmic: Moon", f: 210.42 },
  { name: "Cosmic: Neptune", f: 211.44 },
  { name: "Organs: Lungs", f: 220 },
  { name: "Chakras: Third Eye (Ajna)", f: 221.23 },
  { name: "Cosmic: Venus", f: 221.23 },
  { name: "Angels: Energy balancer", f: 222 },
  {
    name: "Healing: Cell growth, tissue regeneration, and pain relief",
    f: 256,
  },
  { name: "Minerals: Sulphur", f: 256 },
  { name: "Minerals: Selenium and Chlorine", f: 272 },
  { name: "Ohm: High Ohm", f: 272.2 },
  { name: "Chakras: Soul star (Vyapini)", f: 272.2 },
  { name: "Organs: Intestines", f: 281 },
  { name: "Solfeggio: Tissue restauration and healing", f: 285 },
  { name: "Organs: Fat Cells", f: 295.8 },
  { name: "Minerals: Potassium", f: 304 },
  { name: "Minerals: Platinum", f: 312 },
  { name: "Organs: Brain", f: 315.8 },
  { name: "Minerals: Gold", f: 316 },
  { name: "Organs: Liver", f: 317.83 },
  { name: "Organs: Kidneys", f: 319.88 },
  { name: "Minerals: Calcium", f: 320 },
  { name: "Organs: Blood", f: 321.9 },
  { name: "Organs: Muscles", f: 324 },
  { name: "Tesla: Healing, balance, and harmony", f: 333 },
  { name: "Angels: Angelic frequency", f: 333 },
  { name: "Minerals: Molybdenum", f: 336 },
  { name: "Minerals: Magnesium", f: 341 },
  { name: "Organs: Bladder", f: 352 },
  { name: "Minerals: Sodium", f: 352, l: 337 },
  { name: "Minerals: Silver", f: 376 },
  { name: "Minerals: Chromium", f: 384 },
  { name: "Solfeggio: Guilt and fear diminishment", f: 396 },
  { name: "Minerals: Manganese", f: 400 },
  { name: "Minerals: Iron", f: 416 },
  { name: "Solfeggio: Trauma healing", f: 417, l: 320 },
  { name: "Organs: Bone", f: 418.3 },
  { name: "Minerals: Iodine", f: 424 },
  { name: "Angels: Spiritual detoxer", f: 444 },
  { name: "Minerals: Silica", f: 448 },
  { name: "Minerals: Copper", f: 464 },
  { name: "Minerals: Phosphorus and Zinc", f: 480 },
  { name: "Organs: Adrenals", f: 492.8 },
  {
    name: "Healing: Mental clarity and concentration, relaxation and sleep, and stress relief",
    f: 512,
  },
  { name: "Solfeggio: Relaxation and sleep improvemen", f: 528 },
  { name: "DNA: Cytocine", f: 537.8 },
  { name: "DNA: Thymine", f: 543.4 },
  { name: "Ohm: Ultra High Ohm", f: 544.4 },
  { name: "DNA: Adenine", f: 545.6 },
  { name: "DNA: Guanine", f: 550 },
  { name: "Angels: Divine change", f: 555 },
  { name: "Solfeggio: Improvement in mental balance", f: 639 },
  { name: "Tesla: Relationships, connection, and communication", f: 639 },
  { name: "Angels: Physical/spiritual balance", f: 666 },
  { name: "Solfeggio: Detoxification of the mind and body", f: 741 },
  { name: "Angels: Divine sound", f: 777 },
  { name: "Solfeggio: Nervousness and anxity relief", f: 852 },
  { name: "Angels: Infinite possibilities", f: 888 },
  { name: "Solfeggio: Increased positive energy and clarity", f: 963 },
  {
    name: "Tesla: Spiritual awakening, divine connection, and transformation",
    f: 999,
  },
  { name: "Angels: Higher self frequency", f: 999 },
  {
    name: "Healing: Balancing the body's energy, improving the immune system, and pain relief",
    f: 1024,
  },
  {
    name: "Solfeggio: Spiritual purification and to help you access higher spiritual realms",
    f: 1152,
  },
  {
    name: "Solfeggio: Spiritual enlightenment, transcendence and ascension",
    f: 2172,
  },
  { name: "Angels: Jacob's ladder", f: 4096 },
  { name: "Angels: Pillar of light", f: 4160 },
  { name: "Angels: Stairway to heaven", f: 4225 },
];
